### ISSUE TITLE
error when creating conda env from yml file

### ISSUE THREAD

**Issue by whitfa99** [raraz15/electronic_music_downloader#7]
I'm getting a ResolvePackageNotFound error on multiple (half of the) packages when I attempt the conda environment creation, because I think the specific build of the package is specified.  If I delete the specific build for a package it resolves fine.  Tried this in linux and windows.

Would you consider using --no-builds when exporting the yml?  There are too many failed packages for me to manually go through the yml file deleting the build.

**Comment by whitfa99** [comment]
I think it's because some of the builds are architecture-specific?

**Comment by raraz15** [comment]
I tried exporting it with --no-builds and --from-history (as suggested by this  [conda page](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment) )

I will look into this in more detail soon but before I do, I should note that I was using a simpler version of this repo years ago with linux and windows. Maybe I can type the packages I installed using pip on Python 3.9 here and it will help you. 

- youtube-dl
- youtube-search-python
- mutagen

the rest came pre installed with initializing a condo environment.

**Comment by whitfa99** [comment]
So I used this on your yml file:
`sed 's/\(.*[[:alnum:]]\)=[[:alnum:]][[:alnum:].-_]*/\1/' environment.yml > env.yml`

as suggested [here](https://stackoverflow.com/questions/55554431/conda-fails-to-create-environment-from-yml), which removed the build part of the packages.

This reduced the list of failed (osx only) packages to a handful, which I manually deleted from the yml:
`Solving environment: failed

ResolvePackageNotFound: 
  - appscript=1.1.2
  - libgfortran=3.0.1
  - python.app=3
  - appnope=0.1.2
  - llvm-openmp=12.0.0
  - dal=2021.5.0
  - xlwings=0.24.9`
  
  ..and now the environment builds fine!  Perhaps using the --no-builds flag when exporting the yml is the way to go (for me at least)
