### ISSUE TITLE
Error with conda environment creation in README

### ISSUE THREAD

**Issue by peter-clark** [raraz15/electronic_music_downloader#8]
In README.md:
This incorrectly attempts to build the conda environment.
`conda create --name emd --file environment.yml
`
Change to this to fix.
`conda create -f environment.yml
`
FIXED VERSION:
[README.md](https://github.com/raraz15/electronic_music_downloader/files/10056234/README.md)

**Comment by raraz15** [comment]
Solved with: "fix conda create bug #9"
